(use-modules (ice-9 pretty-print))

(define input (read))
(define dim (length input))
(define arr (make-array #\. dim dim))

(define (print-grid g)
  (pretty-print g #:display? #t))

(define x 0)
(define y 0)
(for-each (lambda (line)
	    (for-each (lambda (char)
			(array-set! arr char y x)
			(set! x (1+ x)))
		      line)
	    (set! y (1+ y))
	    (set! x 0))
	  input)

(display input)(newline)
(print-grid arr)

(define (n-adjacent? arr x y)
  (define nx 0)
  (define ny 0)
  (if (> y 0)
      (if (eq? (array-ref arr x (1- y)) #\#)
	  (set! ny (1+ ny))))
  (if (< y dim)
      (if (eq? (array-ref arr x (1+ y)) #\#)
	  (set! ny (1+ ny))))
  (if (> x 0)
      (if (eq? (array-ref arr (1- x) y) #\#)
	  (set! ny (1+ nx))))
  (if (< x dim)
      (if (eq? (array-ref arr (1- x) y) #\#)
	  (set! ny (1+ nx))))
  (+ nx ny))
